name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b600549f550afa6a18e18dffbbf55001fdc2d467fef6b5a4aa17774e1a5953e1"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
