name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7b42238ffe90572a967e5b995b323206449571bbd70d805986b71e9ec937097"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
