name = "Gon"
author = "P1x3l101"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee027e6005933f1b73e23e295a33d7baf7989e48ba5f6349ed6cfce3d77f25bc"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
