name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0822b876b704449ae14b1988d0dcc303080257d63b3fb5419a7aac61f620471c"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
