name = "Gon"
author = "P1x3l101"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "875c6b56779a0f67de0be79e50814f074c2cbd1c1bd567e3491114fbb2eed028"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
