name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77a0834bf59c0a7226785c1ca246d6e8124791f6d37ab52c8ebf349137a28271"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
