name = "Gon"
author = "P1x3l101"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "561459b2d375ba6174b038579f375d72a4d0a89f40aac776c0d2daf9cef9cfe8"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
unsup = "1.1.5"
