enablePinning = true
keepCentered = true
settingsButton = true
enableBook = true

[newRecipes]
unlockAll = false
enableBounce = false

[instantCraft]
showButton = false
enabled = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
