#How much Grime is consumed to make a single unit of Alchemical Waste when cleaning an alchemical device.
#Range: > 1
grimePerWaste = 1200
#At what percent full of Grime that alchemical devices start to lose Efficiency and gain Operation Time.
#Range: 1 ~ 100
grimePenaltyPoint = 50
#How many mB of Academic Slurry constitutes one experience point.
#Range: 1 ~ 1000
fluidPerXPPoint = 100
#How many experience points a Studying construct generates from simple study materials.
#Range: > 1
constructStudyExperienceSimple = 12
#How many experience points a Studying construct generates from advanced study materials.
#Range: > 2
constructStudyExperienceAdvanced = 40
#How many experience points a Studying construct generates from master study materials.
#Range: > 4
constructStudyExperienceMaster = 145
#The Efficiency that Nigredo, Albedo, Citrinitas, and Rubedo receive during distillation. A percentage of the distance between the actual device Efficiency and 100% Efficiency.
#Range: 0 ~ 100
houseOfAlchemyDistillationEfficiencyBonus = 50
#Can Azoth destroy bedrock?
canAzothDestroyBedrock = true
#The amount of Academic Slurry, in mB, consumed to perform Fixation on a first-order Admixture.
#Range: > 10
fixationBaseSlurryCost = 40
#The percent cost increase over base that higher order Admixtures take to perform Fixation. This cost increase is multiplicative.
#Range: > 10
fixationSlurryCompoundCost = 300
#The percent of the experience cost to perform Fixation that is reduced if the process fails.
#Range: 0 ~ 100
fixationFailureRefund = 70
#The baseline efficiency of an Alembic.
#Range: 1 ~ 100
alembicEfficiency = 30
#The time, in ticks, that it takes for an Alembic to process one object.
#Range: > 1
alembicOperationTime = 200
#The maximum Grime level of the Alembic. 
#Range: > 100
alembicGrimeMaximum = 24000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
alembicGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
alembicGrimeOnFailure = 10
#How much higher, as a percent, that the Alembic's Grime meter is treated for the purpose of making Alchemical Waste.
#Range: 0 ~ 900
alembicBonusWaste = 100
#How much fluid, in mB, an Alembic can hold.
#Range: > 1000
alembicTankCapacity = 4000
#The baseline efficiency of a Distillery.
#Range: 1 ~ 100
distilleryEfficiency = 35
#The time, in ticks, that it takes for a Distillery to process one object.
#Range: > 1
distilleryOperationTime = 160
#The maximum Grime level of the Distillery. 
#Range: > 100
distilleryGrimeMaximum = 40000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
distilleryGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
distilleryGrimeOnFailure = 10
#How much fluid, in mB, a Distillery can hold.
#Range: > 1000
distilleryTankCapacity = 8000
#The baseline efficiency of a Centrifuge.
#Range: 1 ~ 100
centrifugeEfficiency = 45
#The time, in ticks, that it takes for a Centrifuge to separate one admixture into component materia.
#Range: > 1
centrifugeOperationTime = 160
#The maximum Grime level of the Centrifuge. 
#Range: > 100
centrifugeGrimeMaximum = 40000
#The amount of Grime generated by an admixture that successfully separates in a Centrifuge.
#Range: > 0
centrifugeGrimeOnSuccess = 75
#The amount of Grime generated by an admixture that fails to separate in a Centrifuge.
#Range: > 0
centrifugeGrimeOnFailure = 10
#The baseline efficiency of a Fusery.
#Range: 1 ~ 100
fuseryEfficiency = 45
#The time, in ticks, that it takes for a Fusery to make one admixture from its component materia.
#Range: > 1
fuseryOperationTime = 160
#The maximum Grime level of the Fusery. 
#Range: > 100
fuseryGrimeMaximum = 40000
#The amount of Grime generated by an admixture that successfully combines in a Fusery.
#Range: > 0
fuseryGrimeOnSuccess = 75
#The amount of Grime generated by an admixture that fails to combine in a Fusery.
#Range: > 0
fuseryGrimeOnFailure = 10
#The amount of Academic Slurry, in mB, the Grand Fusery's internal tank can hold.
#Range: > 500
fuseryTankCapacity = 4000
#The baseline efficiency of a Grand Distillery.
#Range: 1 ~ 100
grandDistilleryEfficiency = 60
#The maximum Grime level of the Grand Distillery. 
#Range: > 100
grandDistilleryGrimeMaximum = 64000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
grandDistilleryGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
grandDistilleryGrimeOnFailure = 10
#How much fluid, in mB, a Grand Distillery can hold.
#Range: > 1000
grandDistilleryTankCapacity = 32000
#The baseline efficiency of a Grand Distillery.
#Range: 1 ~ 100
grandCentrifugeEfficiency = 60
#The maximum Grime level of the Grand Distillery. 
#Range: > 100
grandCentrifugeGrimeMaximum = 64000
#The amount of Grime generated by a dram of materia that successfully distills.
#Range: > 0
grandCentrifugeGrimeOnSuccess = 75
#The amount of Grime generated by a dram of materia that fails to distill.
#Range: > 0
grandCentrifugeGrimeOnFailure = 10
#The baseline efficiency of a Grand Fusery.
#Range: 1 ~ 100
grandFuseryEfficiency = 60
#The maximum Grime level of the Grand Fusery.
#Range: > 100
grandFuseryGrimeMaximum = 64000
#The amount of Grime generated by an admixture that successfully combines in a Grand Fusery.
#Range: > 0
grandFuseryGrimeOnSuccess = 75
#The amount of Grime generated by an admixture that fails to combine in a Grand Fusery.
#Range: > 0
grandFuseryGrimeOnFailure = 10
#The amount of Academic Slurry, in mB, the Alchemical Nexus's internal tank can hold.
#Range: > 500
alchemicalNexusTankCapacity = 12000
#How much FE/tick the Circle of Power generates when it has one reagent
#Range: > 1
circlePowerGen1 = 75
#How much FE/tick the Circle of Power generates when it has two reagents
#Range: > 2
circlePowerGen2 = 750
#How much FE/tick the Circle of Power generates when it has three reagents
#Range: > 3
circlePowerGen3 = 7500
#How much FE/tick the Circle of Power generates when it has all four reagents
#Range: > 4
circlePowerGen4 = 75000
#Should the first Circle of Power reagent (Grains of Quicksilver) function forever without requiring reprocessing?
circlePowerReprocessing1Eternal = false
#Should the second Circle of Power reagent (Focusing Catalyst) function forever without requiring reprocessing?
circlePowerReprocessing2Eternal = false
#Should the third Circle of Power reagent (Amplifying Prism) function forever without requiring reprocessing?
circlePowerReprocessing3Eternal = true
#Should the last Circle of Power reagent (Auxiliary Circle Array) function forever without requiring reprocessing?
circlePowerReprocessing4Eternal = true
#How many ticks of activity the Circle of Power stores at once
#Range: 1 ~ 72000
circlePowerBuffer = 3
#How many ticks of activity the Circle of Toil stores at once
#Range: 1 ~ 72000
circleToilBuffer = 3
#How much fluid, in mB, a Circle of Fabrication can hold
#Range: > 1000
circleFabricationTankCapacity = 8000
#How much fluid, in mB, a Grand Circle of Fabrication can hold
#Range: > 1000
GrandCircleFabricationTankCapacity = 32000
#How much of one type of Essentia can be stored inside of a Materia Jar.
#Range: > 64
materiaJarEssentiaCapacity = 720
#How much of one type of Admixture can be stored inside of a Materia Jar.
#Range: > 64
materiaJarAdmixtureCapacity = 360
#How much of one type of Essentia can be stored inside of a Materia Vessel.
#Range: > 64
materiaVesselEssentiaCapacity = 3600
#How much of one type of Admixture can be stored inside of a Materia Vessel.
#Range: > 64
materiaVesselAdmixtureCapacity = 1800
#The amount of time, in ticks, that actuators take in between drawing Eldrin power or consuming materia units when only one of the two is present.
#Range: > 1
actuatorSingleSuppliedPeriod = 300
#The amount of time, in ticks, that actuators take in between drawing Eldrin power and consuming materia units when both are present.
#Range: > 1
actuatorDoubleSuppliedPeriod = 1200
#The amount of materia units that an actuator can store.
#Range: > 1
actuatorMateriaBufferMaximum = 400
#The number of materia units that an Actuator gets from a single dram of materia
#Range: > 1
actuatorMateriaUnitsPerDram = 40
#The amount of FE per tick that must be supplied to a Proto-Actuator.
#Range: > 1
protoActuatorFECost = 20
#The amount of Water and Steam, in mB, the Deluge Purifier's internal tanks can hold.
#Range: > 500
delugePurifierTankCapacity = 5000
#The amount of Smoke, in mB, the Inferno Engine's internal tank can hold.
#Range: > 500
infernoEngineTankCapacity = 5000
#The amount of sand that can be stored in the Quake Refinery's internal buffer.
#Range: > 500
quakeRefinerySandCapacity = 16000
#The amount of Grime that can be stored in the Quake Refinery's internal buffer.
#Range: > 500
quakeRefineryGrimeCapacity = 128000
#What percentage of Grime reduced by a Quake Refinery becomes Rarefied Waste instead of Alchemical Waste.
#Range: 1 ~ 100
quakeRefineryRarefiedRate = 40
#The amount of Smoke and Steam, in mB, the Gale Pressurizer's internal tanks can hold.
#Range: > 500
galePressurizerTankCapacity = 5000
#The amount of Academic Slurry, in mB, the Gale Pressurizer's internal tanks can hold.
#Range: > 500
occultMatrixTankCapacity = 72000
#The amount of time, in ticks, that it takes for a Coloring Cauldron with one dye to color an item. This time is exponentially reduced with more dyes down to a quarter at 15 dyes.
#Range: > 10
coloringCauldronBaseOperationTime = 300
#The number of items that a Coloring Cauldron can color per unit of dye when in positive mode.
#Range: > 1
coloringCauldronPositiveCharges = 3
#The number of items that a Coloring Cauldron can color per unit of dye when in positive mode.
#Range: > 1
coloringCauldronNegativeCharges = 5
#The amount of time, in ticks, a Variegator requires to dye something if there is insufficient dye/Admixture of Color.
#Range: > 1
variegatorOperationTimeSlow = 300
#The amount of time, in ticks, a Variegator requires to dye something if appropriate dye/Admixture of Color is provided.
#Range: > 1
variegatorOperationTimeFast = 40
#What percentage the crafting time is reduced by if both Admixture of Color and a full bar of the appropriate dye are present. This is linearly reduced with the fill of the dye gauge.
#Range: 0 ~ 99
variegatorMatchedColorTimeDiscount = 80
#The number of units each of the Variegator's dye gauges can hold.
#Range: > 1
variegatorMaxDye = 250
#How many units of dye each dye item inserted into the Variegator is worth.
#Range: 1 ~ 64
variegatorDyePerItem = 10
#The number of units the Variegator's Admixture of Color gauge can hold.
#Range: > 1
variegatorMaxAdmixture = 600
#How many units of dye each dram of Admixture of Color inserted into the Variegator is worth.
#Range: 1 ~ 64
variegatorAdmixturePerItem = 15
#The maximum capacity of the Conjurer's materia gauge.
#Range: > 1
conjurerMateriaCapacity = 100
#The number of points that a single dram of materia adds to the materia gauge.
#Range: > 1
conjurerPointsPerDram = 4
#What percentage a Skywrath Altar will recharge an object's FE gauge to. Only used if this value would be less than the recharge limit below.
#Range: > 1
skywrathAltarFEChargePercentage = 50
#The maximum amount of FE a Skywrath Altar will recharge an object's FE gauge by. Only used if this value would be greater than the recharge percentage above.
#Range: > 1
skywrathAltarFEChargeLimit = 30000
#The number of materia units that a Skywrath Condenser gets from a single dram of materia
#Range: > 1
skywrathCondenserMateriaUnitsPerDram = 40
#How many materia units are consumed by a Skywrath Altar when a craft is triggered by Lightning Damage
#Range: > 1
skywrathCondenserLightningTriggerCost = 30
#How many materia units are consumed by a Skywrath Altar when a craft is triggered by a redstone signal
#Range: > 1
skywrathCondenserRedstoneTriggerCost = 120
#How many Lumins an object gains when using a standard glass lens during a correct celestial phase
#Range: > 1
astralObserverLuminGainStandard = 20
#How many Lumins an object gains when using a cloister lens during a correct celestial phase
#Range: > 1
astralObserverLuminGainCloister = 12
#How many Lumins an object gains when using a standard glass lens during a correct celestial phase
#Range: > 1
astralObserverLuminGainFarsight = 8
#How many Lumins an object loses when using a standard glass lens during incorrect celestial phases
#Range: > 1
astralObserverLuminLoss = 5
#The amount of Water and Steam, in mB, both of the Acid Basin's internal tanks can hold.
#Range: > 1
acidBasinTankCapacity = 5000
#How many units does a single dram of 
#Reminder, one unit is one point of durability damage to inserted items.
#Range: > 1
disintegrationPyreMateriaUnitsPerDram = 500
#The maximum length in any one axis that the Materia Manifest will allow from a Rune of Marking Pair.
#Range: > 1
materiaManifestSizeConstraint = 40
#The maximum distance from the center of the Rune of Marking Pair that a Materia Manifest can be. Set to 0 for no limit.
#Range: > 0
materiaManifestDistanceLimit = 150
#The default cuboid range that a Materia Manifest searches for containers in. The center block is not counted as part of this squadius.
#Range: > 1
materiaManifestDefaultRange = 8
#The default cuboid range that a Slumbering Idol will slaughter Phantoms in.
#Range: 16 ~ 1024
slumberingIdolRange = 64
#A comma separated list of English admixture names. Disables Prophecies of that type of materia from being started. Use the name alone without a prefix, e.g. disaster instead of admixture_disaster.
gnosticOrbProphecyBlacklist = []
#A comma separated list of component registry names that ignore boosts to Damage from the Wisdom Stones.
wisdomBlacklistDamage = []
#A comma separated list of component registry names that ignore boosts to Delay from the Wisdom Stones.
wisdomBlacklistDelay = []
#A comma separated list of component registry names that ignore boosts to Duration from the Wisdom Stones.
wisdomBlacklistDuration = []
#A comma separated list of component registry names that ignore boosts to Lesser Magnitude from the Wisdom Stones.
wisdomBlacklistLesserMagnitude = []
#A comma separated list of component registry names that ignore boosts to Magnitude from the Wisdom Stones.
wisdomBlacklistMagnitude = ["mna:components/shield", "mna:components/simulacrum"]
#A comma separated list of component registry names that ignore boosts to Radius from the Wisdom Stones.
wisdomBlacklistRadius = []
#A comma separated list of component registry names that ignore boosts to Range from the Wisdom Stones.
wisdomBlacklistRange = []
#A comma separated list of component registry names that ignore boosts to Speed from the Wisdom Stones.
wisdomBlacklistSpeed = []

